### ISSUE TITLE
load cells as a standalone "Spreadsheet with JavaScript scripting"

### ISSUE THREAD

**Issue by crisdosaygo** [i5ik/_____#27]
hahaha

maybe I should put it in a webworker first

**Comment by i5ik** [comment]
- [ ] style properly
- [ ] multi-selection (like excel for copy paste), 
- [ ] import and export (csv -- use csv parsing library)
- [ ] import and export using API (programmatically input and output data)
- [ ] column / row dragging for width / height
- [ ] size dragging also on mobile
- [ ] cell sorting (ascending / descending)

later: 
- [ ] implement proper change propagation, by getting used variables using the proxy (somehow)
- [ ] consider doing compute inside a webworker to isolate from main thread and from DOM
