### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by crisdosaygo** [i5ik/_____#39]
- [x] support passive event listeners
- [x] load only a small window out of infinite number of rows and columns
- [ ] try preview / commit two phase resizing for performance and to avoid scroll snap jank issues
- [x] alternately try switching off scroll snap during resize dragging

**Comment by i5ik** [comment]
inspire by the sproutcore big data demo for how to do the infinite https://showcase.sproutcore.com/#demos/Big%20Data%20Lists
